[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# for zysync reployments these were added
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
evm_version = "paris"
zksolc_version = "1.3.19"

[profile.zksync]
evm_version = "paris"
viaIr = true
optimizer = true
optimizer_runs = 200
zksolc_version = "1.3.19"
force_evmla = true

[rpc_endpoints]
zksync_testnet = "${ZKSYNC_ERA_TESTNET_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
